### ISSUE TITLE
SQLite: Foreign key constraint failed on generation

### ISSUE THREAD

**Issue by sheridanchris** [jacentino/SqlFun#20]
```fs
type UserSession = {
  Session: string
  UserId: int
  ExpiresAt: DateTime
}

let saveUserSession: UserSession -> AsyncDb<unit> =
  sql "INSERT INTO UserSessions (Session, UserId, ExpiresAt) VALUES (@Session, @UserId, @ExpiresAt);"
```

```
Unhandled exception. System.TypeInitializationException: The type initializer for '<StartupCode$IssueTracker>.$Login' threw an exception.
 ---> SqlFun.Exceptions.CompileTimeException: Error generating function UserSession -> IDataContext -> unit Async for sql command INSERT INTO UserSessions (Session, UserId, ExpiresAt) VALUES (@Session, @UserId, @ExpiresAt);
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at SqlFun.Queries.makeDiagnosticCall@347(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, String commandText, FSharpList`1 paramDefs)
   at SqlFun.Queries.genExecutor@372[a](FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, a createCommand@372, FSharpList`1 paramDefs, Type returnType)
   at SqlFun.Queries.generateSqlCommandCaller(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 extractParameterNames, FSharpFunc`2 paramBuilder, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, Type t)
   --- End of inner exception stack trace ---
   at SqlFun.Queries.generateSqlCommandCaller(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 extractParameterNames, FSharpFunc`2 paramBuilder, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, Type t)
   at SqlFun.Queries.sql[t](GeneratorConfig config, String commandText)
   at Sql.sql[a](String commandText) in /home/christian/Programming/issue-tracker/src/IssueTracker/Sql.fs:line 32
   at <StartupCode$IssueTracker>.$Login..cctor() in /home/christian/Programming/issue-tracker/src/IssueTracker/Authentication/Login.fs:line 44
   --- End of inner exception stack trace ---
   at Login.get_handler()
   at <StartupCode$IssueTracker>.$Program.main@() in /home/christian/Programming/issue-tracker/src/IssueTracker/Program.fs:line 23
```

**Comment by jacentino** [comment]
I prepared a fix. It's available on nuget as SqlFun 2.3.0.
Since the issue occurs only when Microsoft.Data.Sqlite is used and works just fine for System.Data.Sqlite, I added configuration modifier ``useMicrosoftDataSqlite``. You can use it as follows:

```F#
    let generatorConfig = 
        createDefaultConfig createConnection 
        |> useMicrosoftDataSqlite
```
