### ISSUE TITLE
Postgresql: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by sheridanchris** [jacentino/SqlFun#21]
```
Unhandled exception. SqlFun.Exceptions.CompileTimeException: Error generating function FeedQuery -> IDataContext -> Post list Async for sql command select * from feeds where name = @FeedName
 ---> System.Exception: No column found for FeedName field. Expected: FeedName
 ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.FSharp.Collections.MapTreeModule.throwKeyNotFound[a]() in D:\a\_work\1\s\src\FSharp.Core\map.fs:line 187
   at Microsoft.FSharp.Collections.MapTreeModule.find[TKey,TValue](IComparer`1 comparer, TKey k, MapTree`2 m) in D:\a\_work\1\s\src\FSharp.Core\map.fs:line 196
   at SqlFun.ResultBuilder.getRowBuilderExpression[a](FSharpFunc`2 nextRB, a reader, FSharpMap`2 metadata, String prefix, String fieldName, Type returnType)
   --- End of inner exception stack trace ---
   at SqlFun.ResultBuilder.getRowBuilderExpression[a](FSharpFunc`2 nextRB, a reader, FSharpMap`2 metadata, String prefix, String fieldName, Type returnType)
   at SqlFun.GeneratorConfigModule.createDefaultConfig@227-3D.Invoke(Type returnType)
   at SqlFun.ResultBuilder.getRowBuilderExpression[a](FSharpFunc`2 nextRB, a reader, FSharpMap`2 metadata, String prefix, String fieldName, Type returnType)
   at SqlFun.GeneratorConfigModule.createDefaultConfig@227-3D.Invoke(Type returnType)
   at SqlFun.ResultBuilder.buildRow(FSharpFunc`2 rowBuilder, FSharpMap`2 metadata, Type returnType)
   at SqlFun.ResultBuilder.buildRow@416.Invoke(FSharpMap`2 metadata, Type returnType)
   at SqlFun.ResultBuilder.buildOneResultSet$cont@417(Boolean isAsync, FSharpMap`2 collectionResultBuilders, FSharpMap`2 metadata, Type returnType, FSharpFunc`2 buildRow, Unit unitVar)
   at SqlFun.ResultBuilder.buildOneResultSet@414(FSharpFunc`2 rowBuilder, Boolean isAsync, FSharpMap`2 collectionResultBuilders, FSharpMap`2 metadata, Type returnType)
   at SqlFun.ResultBuilder.generateResultBuilder(FSharpFunc`2 rowBuilder, FSharpList`1 metadata, Type returnType, Boolean isAsync)
   at SqlFun.Queries.genExecutor@372[a](FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, a createCommand@372, FSharpList`1 paramDefs, Type returnType)
   at SqlFun.Queries.generateSqlCommandCaller(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 extractParameterNames, FSharpFunc`2 paramBuilder, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, Type t)
   --- End of inner exception stack trace ---
   at SqlFun.Queries.generateSqlCommandCaller(FSharpFunc`2 createConnection, FSharpFunc`2 createCommand, FSharpOption`1 commandTimeout, FSharpFunc`2 extractParameterNames, FSharpFunc`2 paramBuilder, FSharpFunc`2 rowBuilder, Boolean makeDiagnosticCalls, String commandText, Type t)
   at SqlFun.Queries.sql[t](GeneratorConfig config, String commandText)
   at Program.sql[a](String commandText) in /home/christian/Programming/YoutubeVideos/RssReader/src/RssReader/Program.fs:line 29
   at <StartupCode$RssReader>.$Program.main@() in /home/christian/Programming/YoutubeVideos/RssReader/src/RssReader/Program.fs:line 77
```

```fs
type FeedQuery = { FeedName: string }

let queryPostsByFeed: FeedQuery -> AsyncDb<Post list> =
  sql "select * from feeds where name = @FeedName"
```

**Comment by sheridanchris** [comment]
I used the wrong type. Not an issue.
